---
- name: Build common names parameter
  include: set_common_names.yml

- name: Issue acme certificate requests with challenge_alias
  command: "{{ certs_root_dir }}/acme.sh/acme.sh --issue {{ cns }} --dns dns_{{ dns_provider }} --server {{ acme_server }} --challenge-alias {{ challenge_alias }}"
  environment: "{{ dns_provider_env }}"
  ignore_errors: yes
  when: challenge_alias is defined and (cns | length) > 0

- name: Issue acme certificate requests
  command: "{{ certs_root_dir }}/acme.sh/acme.sh --issue {{ cns }} --dns dns_{{ dns_provider }} --server {{ acme_server }}"
  environment: "{{ dns_provider_env }}"
  ignore_errors: yes
  when: challenge_alias is not defined and (cns | length) > 0

- name: Create certificates directory if it does not exist
  file:
    path: "{{ certs_root_dir }}/certificates"
    state: directory
    mode: '0755'
  when: (cns | length) > 0

- name: Copy certificate requests
  command: "{{ certs_root_dir }}/acme.sh/acme.sh --install-cert {{ cns }} --key-file {{ certs_root_dir }}/certificates/key.pem --fullchain-file {{ certs_root_dir }}/certificates//fullchain.pem --ca-file {{ certs_root_dir }}/certificates//ca.cer"
  when: (cns | length) > 0
